name: todo_simple
description: KashishAggarwal_102103490_APK

publish_to: 'none'

version: 1.4.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  iconly: ^1.0.1
  flutter_speed_dial: ^6.0.0

  sqflite:
  path:

  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  image_path: "assets/Adobe_Express_20220623_1425300.804553760356139.png"
  adaptive_icon_background: "assets/Adobe_Express_20220625_1726210.825601856833301.png"
  adaptive_icon_foreground: "assets/icon-foreground-432x432.png"


flutter:

  uses-material-design: true